version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "pass_admin_123"
      MYSQL_DATABASE: "libreria"
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  uttt-micro-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=libreria;user=root;password=pass_admin_123
    depends_on:
      - mysql
    networks:
      - default

volumes:
  mysql_data:

networks:
  default:
    driver: bridge