version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "pass_admin_123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  uttt-micro-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=libreria;User Id=sa;Password=pass_admin_123;TrustServerCertificate=True;
    depends_on:
      - sqlserver