services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "pass_admin_123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "libreria_autores"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  autor-api:
    build: .
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=libreria_autores;Username=postgres;Password=pass_admin_123;
    ports:
      - "8080:8080"

volumes:
  postgres_data: