version: '3.8'

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;
      - Jwt__Key=MiClaveSecretaParaJWT123456789012345678901234567890
      - Jwt__Issuer=AuthMicroservice
      - Jwt__Audience=AuthMicroservice
    depends_on:
      - sqlserver
    networks:
      - auth-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - auth-network

volumes:
  sqlserver_data:

networks:
  auth-network:
    driver: bridge
